/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Button;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author erofa
 */
public class VistaAsientos extends javax.swing.JFrame implements ActionListener {

    int FILAS = 15;
    int COLUMNAS = 25;
    JButton[][] BUTACA;

    public VistaAsientos() throws IOException {
        initComponents();
        setMatriz();
    }

    private void setMatriz() throws IOException {

        BUTACA = new JButton[FILAS][COLUMNAS];
        int x = 10;
        int y = 10;

        for (int i = 0; i < FILAS; i++) {
            for (int j = 0; j < COLUMNAS; j++) {
                 
                BUTACA[i][j] = new JButton();
               
//                establecerImagenInicial(BUTACA[i][j]);
                try {
                    Image img = ImageIO.read(getClass().getResource("Asiento.png"));
                    BUTACA[i][j].setIcon(new ImageIcon(img));
                } catch (Exception ex) {
                    System.out.println("No esta esa onda");
                }
                BUTACA[i][j].setBounds(y, x, 40, 40);
                BUTACA[i][j].setBackground(Color.WHITE);
                 BUTACA[i][j].addActionListener(this);
                butaca.add(BUTACA[i][j]);
                y += 40;
            }
            x += 40;
            y = 10;
            
            
            
           
        }
         
        
        
    }
    
    
    
    

    
    @Override
  public void actionPerformed(ActionEvent e){
      for(int i = 0; i<FILAS; i++){
          for(int j=0; j<COLUMNAS; j++){
              if(e.getSource()==BUTACA[i][j]){
                  try {
                      cambiarEstadoAsiento();
                  } catch (IOException ex) {
                     // Logger.getLogger(VistaAsientos.class.getName()).log(Level.SEVERE, null, ex);
                  }
                 
              }
          }
      }
      
  }
  
  public void cambiarEstadoAsiento() throws IOException{
    for(int i = 0; i<FILAS; i++){
          for(int j=0; j<COLUMNAS; j++){
              try {
                    Image imge = ImageIO.read(getClass().getResource("AsientoVerde.png"));
                    BUTACA[i][j].setIcon(new ImageIcon(imge));
                } catch (Exception e) {
                    System.out.println("No esta esa onda");
                }
          }
      }  
  }
    
    
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butaca = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout butacaLayout = new javax.swing.GroupLayout(butaca);
        butaca.setLayout(butacaLayout);
        butacaLayout.setHorizontalGroup(
            butacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        butacaLayout.setVerticalGroup(
            butacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaAsientos().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VistaAsientos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel butaca;
    // End of variables declaration//GEN-END:variables
}
